{
 "title": "gi",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pages crawled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(crawler_crawled[1m])" }
   ]
  },
  {
   "title": "Active go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg_over_time(go_goroutines[1m]))"
    }
   ]
  },
  {
   "title": "Crawled pages total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(crawler_crawled)" }
   ]
  }
 ]
}