version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
      # - discovery.seed_hosts = ["localhost", "127.0.0.1"]
    ports:
      - "9200:9200"
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda
    ports:
      - 8081:8081
      - 9092:9092
    command:
      - 'redpanda start'
      - '--smp 1'
      - '--overprovisioned'
      - '--kafka-addr 0.0.0.0:9092'
      - '--advertise-kafka-addr 0.0.0.0:9092'
      - '--pandaproxy-addr 0.0.0.0:8082'
      - '--advertise-pandaproxy-addr 0.0.0.0:8082'
