version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
      - discovery.seed_hosts = ["localhost", "127.0.0.1"]
    ports:
      - "9200:9200"
