GET http://localhost:9200/seek/_search HTTP/1.1
Content-Type: application/json

{
  "query": {
    "fuzzy": {
      "Content": {
        "value": "debian"
      }
    }
  },
  "highlight": {
    "fields": {
      "Content": {}
    }
  }
}