scrape_configs:
- job_name: crawler
  scrape_interval: 10s
  static_configs:
  - targets:
    - wikicrawler:8081
- job_name: benthos-publisher
  scrape_interval: 10s
  static_configs:
  - targets:
    - benthos-in:4196